FROM mediaset-spark-aws-glue-demo-builder

ENV SPARK_VERSION=3.1.2
ENV HADOOP_VERSION=3.3.0

ENV SPARK_HOME=/opt/spark
ENV PYTHONPATH="/opt/spark/python/lib/pyspark.zip:/opt/spark/python/lib/py4j-0.10.9-src.zip:/opt/spark/python"

COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN rm -f requirements.txt

COPY dist/spark-${SPARK_VERSION}-bin-hadoop-${HADOOP_VERSION}-glue.tgz /opt/.
RUN tar -xzf /opt/spark-${SPARK_VERSION}-bin-hadoop-${HADOOP_VERSION}-glue.tgz -C /opt \
 && mv /opt/spark-${SPARK_VERSION}-bin-hadoop-${HADOOP_VERSION}-glue /opt/spark \
 && rm -rf /opt/spark-${SPARK_VERSION}-bin-hadoop-${HADOOP_VERSION}-glue.tgz \
 && mkdir /tmp/spark-events

WORKDIR /opt/spark
CMD /opt/spark/sbin/start-history-server.sh && bash